//! Diffusion-specific routing helpers.
//!
//! `/v1/videos` is stateful: a POST creates a job on one worker and stores it
//! in that worker's process-local memory. Follow-up GET / DELETE / `/content`
//! calls must reach the same worker, but the task id alone gives the router
//! no way to recover the worker — so we keep a sticky `task_id → worker_url`
//! map alongside the worker registry.
//!
//! `/v1/images/*` endpoints are synchronous: they return the generated bytes
//! directly with no follow-up endpoints, so they're routed by model but not
//! recorded in the sticky map.

pub mod task_routing;

pub use task_routing::{TaskId, TaskWorkerMap};
